import fs from "fs";
import path from "path";
import chalk from "chalk";

import { checkPrereq } from "../utils.js";
function exportVision() {
  const projectroot = process.cwd();
  const devarchitectdir = path.join(projectroot, ".devarchitect");
  const visionPath = path.join(devarchitectdir, "vision.json");
  const analysisPath = path.join(devarchitectdir, "analyse.json");
  const stackPath = path.join(devarchitectdir, "stack.json");
  const roadmapPath = path.join(devarchitectdir, "roadmap.json");
  const decisionsPath = path.join(devarchitectdir, "decisions.json");
  const progressPath = path.join(devarchitectdir, "progress.json");

  checkPrereq("vision.json", "init");

  const visionFileData = fs.readFileSync(visionPath, "utf-8");
  const dataVision = JSON.parse(visionFileData);

  let dataAnalysis;
  let dataStack;
  let dataRoadmap;
  let dataDecisions;
  let dataProgress;

  //try for analysis
  try {
    const analysisFileData = fs.readFileSync(analysisPath, "utf-8");

    dataAnalysis = JSON.parse(analysisFileData);
  } catch (err) {
    dataAnalysis = null;
  }
  //try for stack
  try {
    const stackFileData = fs.readFileSync(stackPath, "utf-8");

    dataStack = JSON.parse(stackFileData);
  } catch (err) {
    dataStack = null;
  }
  //try for roadmap
  try {
    const roadmapFileData = fs.readFileSync(roadmapPath, "utf-8");

    dataRoadmap = JSON.parse(roadmapFileData);
  } catch (err) {
    dataRoadmap = null;
  }
  //try for decision
  try {
    const decisionFileData = fs.readFileSync(decisionsPath, "utf-8");

    dataDecisions = JSON.parse(decisionFileData);
  } catch (err) {
    dataDecisions = null;
  }
  // try for progress
  try {
    const progressFileData = fs.readFileSync(progressPath, "utf-8");

    dataProgress = JSON.parse(progressFileData);
  } catch (err) {
    dataProgress = null;
  }

  let decisionCount = 0;

  // ${!==null?``:`Not yet defined`}

  const mdString = `# Project Report - ${dataVision.projectname}\n

Generated on on ${new Date().toLocaleDateString()}

---

## Vision
- Problem: ${dataVision.problem}
- Target: ${dataVision.target}
- Platform: ${dataVision.platform}
- Team Size: ${dataVision.teamsize}

---

## Feasibility Analysis
${
  dataAnalysis !== null
    ? `- Technical Risks: ${dataAnalysis.techrisk}
- Project Timeline: ${dataAnalysis.timeline}
- Project Scale: ${dataAnalysis.scale}
- Project Budget: ${dataAnalysis.budget}
`
    : `- Not yet defined`
}
---

## Tech Stack
${
  dataStack !== null
    ? `- Frontend: ${dataStack.frontend}
- Backend: ${dataStack.backend}
- Database: ${dataStack.database}
- Deployment: ${dataStack.deployment}
- Other Tools: ${dataStack.tools}
`
    : `- Not yet defined`
}
---

## Roadmap
${
  dataRoadmap !== null
    ? `${dataRoadmap.phaseArray
        .map(
          ({ phase, name, milestones }) => `
### Phase: ${phase}
- Name: ${name}
- Milestones: [ ${milestones} ]
`,
        )
        .join("")}`
    : `- Not yet defined`
}
---

## Decisions Log
 ${
   dataDecisions !== null
     ? `${dataDecisions
         .map(
           ({ what, why, decidedAt }) => `
### Decision ${++decisionCount}
- Decision: ${what}
- Reason: ${why}
- Decided on: ${decidedAt}
`,
         )
         .join("")}`
     : `- Not yet defined`
 }
---

## Current Progress
${
  dataProgress !== null
    ? `- Current Phase: ${dataProgress[dataProgress.length - 1].currentPhase}
- All Phases: ${dataProgress[dataProgress.length - 1].allPhases}
- Completed Milestones: ${dataProgress[dataProgress.length - 1].completedMilestones}
- Blockers: ${dataProgress[dataProgress.length - 1].blockers}
- Completion: ${dataProgress[dataProgress.length - 1].completion} 
- Recorded At: ${dataProgress[dataProgress.length - 1].recordedAt}`
    : `- Not yet defined`
}
---

Generated by devarchitect `;

  fs.writeFileSync(`${projectroot}/devarchitect-report.md`, mdString, "utf-8");
  console.log(chalk.yellow("Saved to devarchitect-report.md"));
}
export { exportVision };
