import fs from "fs";
import path from "path";
import chalk from "chalk";
function exportVision() {
  const projectroot = process.cwd();
  const devarchitectdir = path.join(projectroot, ".devarchitect");
  const visionPath = path.join(devarchitectdir, "vision.json");
  if (!fs.existsSync(visionPath)) {
    console.log(chalk.red("Please run devarchitect init first!"));
    process.exit(1);
  }
  const visionFileData = fs.readFileSync(visionPath, "utf-8");
  const data = JSON.parse(visionFileData);
  // console.log(data);
  const mdString = `# Project Report - ${data.projectname}\n
## Vision
- Problem: ${data.problem}
- Target: ${data.target}
- Platform: ${data.platform}
- Team Size: ${data.teamsize}
- Created At: ${data.createdat}\n
Generated by devarchitect on ${new Date().toLocaleDateString()}`;
  // console.log(mdString);

  fs.writeFileSync(`${projectroot}/devarchitect-report.md`, mdString, "utf-8");
  console.log(chalk.yellow("Saved to devarchitect-report.md"));
}

export { exportVision };
