import fs from "fs";
import path from "path";
import chalk from "chalk";

import { checkPrereq } from "../utils.js";
function exportVision() {
  const projectroot = process.cwd();
  const devarchitectdir = path.join(projectroot, ".devarchitect");
  const visionPath = path.join(devarchitectdir, "vision.json");
  const analysisPath = path.join(devarchitectdir, "analyse.json");
  const stackPath = path.join(devarchitectdir, "stack.json");
  const roadmapPath = path.join(devarchitectdir, "roadmap.json");

  checkPrereq("vision.json", "init");

  const visionFileData = fs.readFileSync(visionPath, "utf-8");
  const analysisFileData = fs.readFileSync(analysisPath, "utf-8");
  const stackFileData = fs.readFileSync(stackPath, "utf-8");
  const roadmapFileData = fs.readFileSync(roadmapPath, "utf-8");

  const dataVision = JSON.parse(visionFileData);
  const dataAnalysis = JSON.parse(analysisFileData);
  const dataStack = JSON.parse(stackFileData);
  const dataRoadmap = JSON.parse(roadmapFileData);

  const mdString = `# Project Report - ${dataVision.projectname}\n
## Vision
- Problem: ${dataVision.problem}
- Target: ${dataVision.target}
- Platform: ${dataVision.platform}
- Team Size: ${dataVision.teamsize}

---

## Feasibility Analysis
- Technical Risks: ${dataAnalysis.techrisk}
- Project Timeline: ${dataAnalysis.timeline}
- Project Scale: ${dataAnalysis.scale}
- Project Budget: ${dataAnalysis.budget}

---

## Tech Stack
- Frontend: ${dataStack.frontend}
- Backend: ${dataStack.backend}
- Database: ${dataStack.database}
- Deployment: ${dataStack.deployment}
- Other Tools: ${dataStack.tools}

---

## Roadmap
${dataRoadmap.phaseArray
  .map(
    ({ phase, name, milestones }) => `
### Phase: ${phase}
- Name: ${name}
- Milestones: \[ ${milestones} \]
`,
  )
  .join("")}
---



Generated by devarchitect on ${new Date().toLocaleDateString()}`;

  fs.writeFileSync(`${projectroot}/devarchitect-report.md`, mdString, "utf-8");
  console.log(chalk.yellow("Saved to devarchitect-report.md"));
}

export { exportVision };
