import fs from "fs";
import path from "path";
import chalk from "chalk";
import inquirer from "inquirer";

async function installHooks() {
  const projectRoot = process.cwd();
  const gitDir = path.join(projectRoot, ".git");
  const hooksDir = path.join(gitDir, "hooks");
  const preCommitPath = path.join(hooksDir, "pre-commit");

  if (!fs.existsSync(gitDir)) {
    console.log(
      chalk.red("Error: This is not a git repository. Run 'git init' first."),
    );
    return;
  }

  if (!fs.existsSync(hooksDir)) {
    fs.mkdirSync(hooksDir, { recursive: true });
  }

  if (fs.existsSync(preCommitPath)) {
    console.log(
      chalk.yellow(
        "Warning: A pre-commit hook already exists in .git/hooks/pre-commit",
      ),
    );

    const answer = await inquirer.prompt([
      {
        type: "confirm",
        name: "overwrite",
        message: "Do you want to overwrite it?",
        default: false,
      },
    ]);

    if (!answer.overwrite) {
      console.log(
        chalk.gray("Installation cancelled. Existing hook was kept."),
      );
      return;
    }
  }

  const hookScript = `#!/bin/sh
# Automatically generated by devarchitect
echo "Running devarchitect drift check..."
devarchitect drift
exit 0
`;

  fs.writeFileSync(preCommitPath, hookScript, "utf-8");
  fs.chmodSync(preCommitPath, 0o755);

  console.log(
    chalk.green("Git pre-commit hook installed at .git/hooks/pre-commit"),
  );
  console.log(
    chalk.gray(
      "'devarchitect drift' will now run automatically before every commit.",
    ),
  );
  console.log(chalk.gray("To remove it later, run: rm .git/hooks/pre-commit"));
}

export default installHooks;
